events {
    worker_connections 1024;
}

stream {
    server {
        listen 443;
        proxy_pass 172.17.0.1:22;
    }
}

http {
    server {
        listen 80;
        root /usr/share/nginx/html;
        index index.html;
    }
}